name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7, linux/amd64
          push: true
          tags: adamsong/ghostbot:latest
